apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "database") }}-config
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "database") | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.database.env.MYSQL_DATABASE | quote }}
  MYSQL_USER: {{ .Values.database.env.MYSQL_USER | quote }}
  init.sql: |-
{{ .Files.Get "files/init.sql" | nindent 4 }}