apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "database") }}-pvc
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "database") | nindent 4 }}
spec:
  storageClassName: ""
  accessModes:
    - {{ index .Values.database.persistence.accessModes 0 }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  selector:
    matchLabels:
      {{- include "helm-chart.componentSelectorLabels" (dict "root" . "component" "database") | nindent 6 }}