all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  children:
    build_server:
      hosts:
        ci-server:
          ansible_host: 192.168.123.80
          ansible_user: typ
          ansible_ssh_private_key_file: ./ci-gitlab.pem
          ansible_become_password: "8"

    database:
      hosts:
        db-server:
          ansible_host: 192.168.123.81
          ansible_user: typ
          ansible_ssh_private_key_file: ./database.pem
          ansible_become_password: "8"
          
    backend:
      hosts:
        be-server:
          ansible_host: 192.168.123.82
          ansible_user: typ
          ansible_ssh_private_key_file: ./backend.pem
          ansible_become_password: "8"
    
    frontend:
      hosts:
        fe-server:
          ansible_host: 192.168.123.83
          ansible_user: typ
          ansible_ssh_private_key_file: ./frontend.pem
          ansible_become_password: "8"