- name: DBServer setup with Docker
  hosts: db-server
  become: yes
  vars:
    db_root_pass: "{{ lookup('env','MYSQL_ROOT_PASSWORD') }}"
    db_name: "{{ lookup('env','MYSQL_DATABASE') }}"
    db_user: "{{ lookup('env','MYSQL_USER') }}"
    db_pass: "{{ lookup('env','MYSQL_PASSWORD') }}"

  tasks:
    - name: Install Docker and Python Docker SDK
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure MySQL named volume exists
      community.docker.docker_volume:
        name: mysql_data
        state: present

    - name: Start MySQL Container
      community.docker.docker_container:
        name: mysql_db
        image: mysql:8.0
        state: started
        restart_policy: always
        ports:
          - "3306:3306" 
        volumes:
          - mysql_data:/var/lib/mysql 
        env:
          MYSQL_ROOT_PASSWORD: "{{ db_root_pass }}"
          MYSQL_DATABASE: "{{ db_name }}"
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_pass }}"
