apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-chart.fullname" . }}
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
data:
  MYSQL_HOST: {{ .Values.database.host | quote }}
  MYSQL_PORT: {{ .Values.database.port | quote }}
  MYSQL_DATABASE: {{ .Values.database.name | quote }}
  MYSQL_USER: {{ .Values.database.user | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.cors.allowedOrigins | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
