{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-chart.fullname" . }}
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
{{- end }}
