apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: typ-2026-backend
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://gitlab.com/NguyenTuKien/typ_2026_be_config.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://gitlab.com/NguyenTuKien/typ_2026_backend.git'
      targetRevision: HEAD
      path: 'backend-chart'
      helm:
        valueFiles:
        - $values/helm-values/values-prod.yml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: typ-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true