apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  namespace: be-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
      containers:
      - name: be-app
        image: ngtukien218/vissmart-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: PORT
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: DATABASE
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: USERNAME
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: be-config
              key: SERVER_ADDRESS
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: PASSWORD
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"