apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: k8s-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home
          securityContext:
            runAsUser: 0
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim