apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: fe-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-web
  template:
    metadata:
      labels:
        app: fe-web
    spec:
      containers:
      - name: fe-web
        image: ngtukien218/vissmart-frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: fe-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: fe-config-volume
        configMap:
          name: fe-config