database:
  name: database
  replicaCount: 1
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  env:
    MYSQL_ROOT_PASSWORD: "rootpassword123"
    MYSQL_DATABASE: "k8s-database"
    MYSQL_USER: "admin"
    MYSQL_PASSWORD: "password123"

backend:
  name: backend
  replicaCount: 1
  image:
    repository: ngtukien218/k8s-backend
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  env:
    MYSQL_PORT: "3306"
    MYSQL_DATABASE: "k8s-database"
    MYSQL_USER: "admin"
    MYSQL_PASSWORD: "password123"
    CORS_ALLOWED_ORIGINS: "*"

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: ngtukien218/k8s-frontend
    tag: "latest"
    pullPolicy: Always
  service:
    type: NodePort
    port: 3000
    nodePort: 30030