apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "backend") }}-config
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
data:
  MYSQL_HOST: {{ .Values.backend.env.MYSQL_HOST | quote }}
  {{- if eq .Values.database.service.type "NodePort" }}
  MYSQL_PORT: {{ .Values.database.service.nodePort | quote }}
  {{- else }}
  MYSQL_PORT: {{ .Values.database.service.port | quote }}
  {{- end }}
  MYSQL_DATABASE: {{ .Values.database.env.MYSQL_DATABASE | quote }}
  MYSQL_USER: {{ .Values.database.env.MYSQL_USER | quote }}
  CORS_ALLOWED_ORIGINS: {{ default "*" .Values.backend.env.CORS_ALLOWED_ORIGINS | quote }}