apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "backend") }}
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.componentSelectorLabels" (dict "root" . "component" "backend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-chart.componentSelectorLabels" (dict "root" . "component" "backend") | nindent 8 }}
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /app/logs"]
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "helm-chart.componentName" (dict "root" . "component" "backend") }}-config
            - secretRef:
                name: {{ include "helm-chart.componentName" (dict "root" . "component" "backend") }}-secret
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/data/backend-logs
            type: DirectoryOrCreate