[prometheus_servers]
192.168.123.111 ansible_user=prometheus ansible_ssh_private_key_file=~/.ssh/id_ed25519

[prometheus_servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
prometheus_port=9090