apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "frontend") }}
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "helm-chart.componentSelectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}