apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "backend") }}-config
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
data:
  MYSQL_HOST: {{ include "helm-chart.componentName" (dict "root" . "component" "database") }}
  MYSQL_PORT: {{ .Values.backend.env.MYSQL_PORT | quote }}
  MYSQL_DATABASE: {{ .Values.backend.env.MYSQL_DATABASE | quote }}
  MYSQL_USERNAME: {{ .Values.backend.env.MYSQL_USER | quote }}
  CORS_ALLOWED_ORIGINS: {{ default "*" .Values.backend.env.CORS_ALLOWED_ORIGINS | quote }}