apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "backend") }}
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    {{- include "helm-chart.componentSelectorLabels" (dict "root" . "component" "backend") | nindent 4 }}