all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  children:
    database:
      hosts:
        db_server:
          ansible_host: 192.168.123.80
          ansible_user: typ
          ansible_ssh_private_key_file: /home/typ/ansible/ssh_keys/database.pem
          ansible_become_password: 8
        
    backend:
      hosts:
        backend_server:
          ansible_host: 192.168.123.81
          ansible_user: typ
          ansible_ssh_private_key_file: /home/typ/ansible/ssh_keys/backend.pem
          ansible_become_password: 8
        
    frontend:
      hosts:
        frontend_server:
          ansible_host: 192.168.123.82
          ansible_user: typ
          ansible_ssh_private_key_file: /home/typ/ansible/ssh_keys/frontend.pem
          ansible_become_password: 8
        