# Docker Hub thông tin đăng nhập và cấu hình chung
docker_registry: ngtukien218
docker_username: ngtukien218
docker_network_name: minilab

# Version
app_tag: "v1.0"

# MySQL Configuration
mysql_image: "mysql:8.0"
mysql_container_name: "mysql"
mysql_volume_name: "mysql-data"

# Backend Configuration
backend_image: "{{ docker_registry }}/vissmart-backend"
backend_container_name: "backend"

# Backend Database Configuration
db_host: "{{ hostvars['db_server'].ansible_host }}"
db_port: "3306"
db_name: "mini_lab_db"
db_user: "mini_lab_user"
db_pass: "securepassword123"
db_root_pass: "rootpassword456"

# Frontend Configuration
frontend_image: "{{ docker_registry }}/vissmart-frontend"
frontend_container_name: "frontend"

# Frontend gọi Backend Configuration
backend_host: "{{ hostvars['backend_server'].ansible_host }}"
backend_port: "8080"
