- name: Frontend restore (run container from :backup image)
  hosts: fe-server
  become: yes

vars:
  registry_image: "{{ lookup('env','CI_REGISTRY_IMAGE') }}"
  ci_registry: "{{ lookup('env','CI_REGISTRY') }}"
  ci_user: "{{ lookup('env','CI_REGISTRY_USER') }}"
  ci_password: "{{ lookup('env','CI_REGISTRY_PASSWORD') }}"

  be_host: "{{ hostvars['be-server'].ansible_host }}"
  be_port: "8080"

tasks:
- name: Ensure Docker is installed
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker
    state: present
    update_cache: yes

- name: Ensure Docker service is started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Login to GitLab Registry
  community.docker.docker_login:
    registry_url: "{{ ci_registry }}"
    username: "{{ ci_user }}"
    password: "{{ ci_password }}"
    reauthorize: false

- name: Pull Frontend backup image
  community.docker.docker_image:
    name: "{{ registry_image }}/frontend:backup"
    source: pull
    force_source: false

- name: Kill existing Frontend Container
  community.docker.docker_container:
    name: frontend
    state: absent
    force_kill: yes

- name: Run Frontend Container from backup image
  community.docker.docker_container:
    name: frontend
    image: "{{ registry_image }}/frontend:backup"
    state: started
    restart_policy: always
    ports:
      - "81:80"
    env:
      BACKEND_HOST: "{{ be_host }}"
      BACKEND_PORT: "{{ be_port }}"

- name: Clean up unused Docker images
  community.docker.docker_prune:
    images: yes
    containers: no
    networks: no
    volumes: no