- name: Backend backup
  hosts: be-server
  become: yes

  vars:
    registry_image: "{{ lookup('env','CI_REGISTRY_IMAGE') }}"
    ci_registry: "{{ lookup('env','CI_REGISTRY') }}"
    ci_user: "{{ lookup('env','CI_REGISTRY_USER') }}"
    ci_password: "{{ lookup('env','CI_REGISTRY_PASSWORD') }}"

  tasks:
  - name: Ensure Docker is installed
    ansible.builtin.apt:
      name:
        - docker.io
        - python3-docker
      state: present
      update_cache: yes

  - name: Ensure Docker service is started
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - name: Login to GitLab Registry
    community.docker.docker_login:
      registry_url: "{{ ci_registry }}"
      username: "{{ ci_user }}"
      password: "{{ ci_password }}"
      reauthorize: false

  - name: Check if backend container exists to get current image
    community.docker.docker_container_info:
      name: backend
    register: backend_info

  - name: Tag current backend image as backup (only if container exists)
    community.docker.docker_image:
      name: "{{ backend_info.container.Config.Image }}"
      repository: "{{ registry_image }}/backend:backup"
      source: local
      push: yes
    when: backend_info.exists