- name: Backend Server Setup
  hosts: be-server
  become: yes
  vars:
    db_host: "{{ hostvars['db-server'].ansible_host }}"
    db_port: "3306"
    db_name: "{{ lookup('env','MYSQL_DATABASE') }}"   # Khớp với db_setup
    db_user: "{{ lookup('env','MYSQL_USER') }}"         # Khớp với db_setup
    db_password: "{{ lookup('env','MYSQL_PASSWORD') }}" # Khớp với db_setup

    registry_image: "{{ lookup('env','CI_REGISTRY_IMAGE') }}"
    tag: "{{ lookup('env','TAG') | default('latest') }}"
    
    ci_registry: "{{ lookup('env','CI_REGISTRY') }}"
    ci_user: "{{ lookup('env','CI_REGISTRY_USER') }}"     
    ci_password: "{{ lookup('env','CI_REGISTRY_PASSWORD') }}" 

  tasks:
  - name: Install Docker and Python SDK
    ansible.builtin.apt:
      name:
        - docker.io
        - python3-docker 
      state: present
      update_cache: yes

  - name: Ensure backend data directories exist (for volume mounts)
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
    loop:
      - /opt/minilab/backend/.m2
      - /opt/minilab/backend/logs

  - name: Ensure Docker service is started
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - name: Log into GitLab Registry
    community.docker.docker_login:
      registry_url: "{{ ci_registry }}"
      username: "{{ ci_user }}"
      password: "{{ ci_password }}"
      reauthorize: yes

  - name: Pull Backend Image
    community.docker.docker_image:
      name: "{{ registry_image }}/backend:{{ tag }}"
      source: pull
      force_source: true
    ignore_errors: yes

  - name: Kill existing Backend Container
    community.docker.docker_container:
      name: backend
      state: absent
      force_kill: yes

  - name: Run Backend Container
    community.docker.docker_container:
      name: backend
      image: "{{ registry_image }}/backend:{{ tag }}"
      state: started
      restart_policy: always
      ports:
        - "8080:8080" 
      volumes:
        - /opt/minilab/backend/.m2:/root/.m2
        - /opt/minilab/backend/logs:/app/logs
      env:
        SERVER_ADDRESS: "0.0.0.0"
        HOST: "{{ db_host }}"      
        PORT: "{{ db_port }}"
        DATABASE: "{{ db_name }}"
        USERNAME: "{{ db_user }}"
        PASSWORD: "{{ db_password }}"

  - name: Clean up unused Docker images
    community.docker.docker_prune:
      images: yes
      containers: no
      networks: no
      volumes: no