- name: Install docker
  apt:
    name:
      - docker.io
      - python3-pip
    update_cache: true
    state: present

- name: Install docker SDK for Ansible
  apt:
    name: python3-docker
    state: present
    update_cache: yes

- name: Ensure docker is started
  service:
    name: docker
    state: started
    enabled: true
