apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "database") }}-secret
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "database") | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.env.MYSQL_ROOT_PASSWORD | quote }}
  MYSQL_PASSWORD: {{ .Values.database.env.MYSQL_PASSWORD | quote }}
  setup.sql: |
    ALTER USER '{{ .Values.database.env.MYSQL_USER }}'@'%' IDENTIFIED WITH mysql_native_password BY '{{ .Values.database.env.MYSQL_PASSWORD }}';
    GRANT ALL PRIVILEGES ON `{{ .Values.database.env.MYSQL_DATABASE }}`.* TO '{{ .Values.database.env.MYSQL_USER }}'@'%';
    FLUSH PRIVILEGES;