apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.componentName" (dict "root" . "component" "database") }}
  labels:
    {{- include "helm-chart.componentLabels" (dict "root" . "component" "database") | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
  selector:
    {{- include "helm-chart.componentSelectorLabels" (dict "root" . "component" "database") | nindent 4 }}
  {{- if eq (.Values.database.service.type | default "ClusterIP") "ClusterIP" }}
  clusterIP: None
  {{- end }}