backend:
  name: backend
  replicaCount: 2
  image:
    repository: ngtukien218/typ-2026-backend
    tag: "v1.5.11"
    pullPolicy: Always
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  env:
    CORS_ALLOWED_ORIGINS: "*"

  ingress:
    enabled: true  
    host: api.typ-app.local  
    tls:
      secretName: vdt-tls-secret  # Tên secret chứa chứng chỉ SSL

database:
  name: typ-2026-database
  service:
    port: 3306

  env:
    MYSQL_HOST: typ-2026-database
    MYSQL_DATABASE: "typ-database"
    MYSQL_USER: "typ-admin"
    MYSQL_PASSWORD: "password123"
