backend:
  name: backend
  replicaCount: 2
  image:
    repository: ngtukien218/typ-2026-backend
    tag: "2073dc8"
    pullPolicy: Always
  service:
    type: NodePort
    port: 8080
    nodePort: 30080
  env:
    MYSQL_HOST: 192.168.123.11
    CORS_ALLOWED_ORIGINS: "*"

database:
  service:
    type: NodePort
    port: 3306
    nodePort: 30336

  env:
    MYSQL_DATABASE: "typ-database"
    MYSQL_USER: "typ-admin"
    MYSQL_PASSWORD: "password123"
